base:
  project: AdmissionPrediction-project
  random_state: 42
  target_col: Chance of Admit

data_source:
  s3_source: data_given/Admission_Prediction.csv

load_data:
  raw_dataset_csv: data/raw/Admission_Prediction.csv.csv

split_data:
  train_path: data/processed/train_Admission.csv
  test_path: data/processed/test_Admission.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.4
model_dir: saved_models